name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prueba-valuetech
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests
        run: dotnet test ValueTech.Tests --logger "console;verbosity=normal"

      - name: Clean Artifacts (bin/obj)
        run: |
          find . -name "bin" -type d -prune -exec rm -rf '{}' +
          find . -name "obj" -type d -prune -exec rm -rf '{}' +

      - name: Copy files to Server (SCP)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: |
            ${{ secrets.SSH_PEM_KEY }}
          source: "."
          target: "/home/ubuntu/valuetech" 
      
      - name: Execute Remote Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: |
            ${{ secrets.SSH_PEM_KEY }}
          debug: true
          script: |
            cd /home/ubuntu/valuetech
            # Ensure Docker is installed or just run compose
            # Force rebuild to pick up new code changes
            docker compose down -v
            docker compose up --build -d
            # Clean up unused images to save disk space
            docker image prune -f
